apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - postgres.yaml
  - redpanda.yaml
  - api.yaml
  - agent-worker.yaml
  - pr-worker.yaml
